---
version: 1.0.0

keystores:
  - name: server
    type: pem
    certificate:
      - label: cert
        content: "@keys/server.pem"
    key:
      - label: key
        content: "@keys/server.key"
  - name: jwks_keys
    type: pem
    certificate:
      - label: jwtsigner
        content: "@keys/jwtsigner.pem"
    key:
      - label: jwtsigner
        content: "@keys/jwtsigner.key"

server_connections: 
  - name: sqlitefile
    type: sqlite
    database_name: ssf
    hosts:
      - hostname: "file:///db/ssf.db?cache=shared"
        hostport: 0

databases:
  config:
    server: sqlitefile
  raw_2_ssf:
    server: sqlitefile
    partitions: 1
  ssf_2_set:
    server: sqlitefile
    partitions: 1
  poll_stage:
    server: sqlitefile
    retention_time_in_days: 4
