apiVersion: v1
kind: Service
metadata:
  name: antenna-transmitter
  labels:
    app: antenna-transmitter
spec:
  selector:
    app: dune-transmitter
  ports:
  - name: port-9042
    port: 9042
    targetPort: 9042
    protocol: TCP
  - name: port-9044
    port: 9044
    targetPort: 9044
    protocol: TCP
  type: ClusterIP
